# -*- coding: utf-8 -*-
"""streamlit_event_stream

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qs85F-KZZmzq0a0kEph0ZcBtM7psg-__

# 4. Hasil Dashboard
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("event_alert_stream.csv")

st.set_page_config(
    page_title='Event Stream Dashboard',
    layout='wide'
)

stream_df = pd.read_csv(
    'event_alert_stream.csv'
)

st.title('Event Stream Monitoring Dashboard')


col1, col2, col3, col4 = st.columns(4)
col1.metric(
    "Total Events",
 len(stream_df)
)

col2.metric(
    "Critical Alerts",
    len(
        stream_df[
            stream_df['alert_level'] == 'CRITICAL'
        ]
    )
)

col3.metric(
    "High Alerts",
    len(
        stream_df[
            stream_df['alert_level'] == 'HIGH'
        ]
    )
)

col4.metric(
    "Unique Users",
    df['user_id'].nunique()
)

st.subheader("Alerts Distribution")

fig, ax = plt.subplots()

df['alert_level'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    ax=ax
)
ax.set_ylabel('')

st.pyplot(fig)

st.subheader("Top Risky User")
top_users = (
    df.groupby('user_id')['risk_score']
    .mean()
    .sort_values(ascending=False)
    .head(10)
)
st.bar_chart(top_users)

st.subheader("Department Risk Score")

dept_risk = (
    df.groupby('dept')['risk_score']
    .mean()
    .sort_values(ascending=False)
)

st.bar_chart(dept_risk)

st.subheader("Data Classification Access")

st.bar_chart(
    df['data_classification']
    .value_counts()
)

st.subheader("Latest Events")

st.dataframe(
    df.tail(20)
)